# Generated by Django 3.2 on 2022-02-14 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TypeOfPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Weeks',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.CharField(blank=True, max_length=254, null=True)),
                ('day2', models.CharField(blank=True, max_length=254, null=True)),
                ('day3', models.CharField(blank=True, max_length=254, null=True)),
                ('day4', models.CharField(blank=True, max_length=254, null=True)),
                ('day5', models.CharField(blank=True, max_length=254, null=True)),
                ('day6', models.CharField(blank=True, max_length=254, null=True)),
                ('day7', models.CharField(blank=True, max_length=254, null=True)),
                ('kind_of_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.typeofplan')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('number_of_weeks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.weeks')),
            ],
            options={
                'verbose_name_plural': 'Plans',
            },
        ),
    ]
