# Generated by Django 3.2 on 2022-01-29 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('week1', models.CharField(max_length=254)),
                ('week2', models.CharField(max_length=254)),
                ('week3', models.CharField(max_length=254)),
                ('week4', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.duration')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.plans'),
        ),
    ]
