# Generated by Django 3.2 on 2022-02-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Weeks',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.CharField(blank=True, max_length=254, null=True)),
                ('day2', models.CharField(blank=True, max_length=254, null=True)),
                ('day3', models.CharField(blank=True, max_length=254, null=True)),
                ('day4', models.CharField(blank=True, max_length=254, null=True)),
                ('day5', models.CharField(blank=True, max_length=254, null=True)),
                ('day6', models.CharField(blank=True, max_length=254, null=True)),
                ('day7', models.CharField(blank=True, max_length=254, null=True)),
                ('kind_of_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.typeofplan')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('number_of_weeks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.weeks')),
            ],
            options={
                'verbose_name_plural': 'Plans',
            },
        ),
    ]
