# Generated by Django 3.2 on 2022-01-29 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220129_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='plan',
        ),
        migrations.AddField(
            model_name='duration',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='week1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='duration',
            name='week2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='duration',
            name='week3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='duration',
            name='week4',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='duration',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
