# Generated by Django 3.2 on 2022-01-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220129_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duration',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
        migrations.DeleteModel(
            name='Duration',
        ),
    ]
