# Generated by Django 3.2 on 2022-01-30 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product'),
        ),
    ]
