# Generated by Django 3.2 on 2022-01-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220130_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('day1', models.CharField(blank=True, max_length=254, null=True)),
                ('day2', models.CharField(blank=True, max_length=254, null=True)),
                ('day3', models.CharField(blank=True, max_length=254, null=True)),
                ('day4', models.CharField(blank=True, max_length=254, null=True)),
                ('day5', models.CharField(blank=True, max_length=254, null=True)),
                ('day6', models.CharField(blank=True, max_length=254, null=True)),
                ('day7', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.AddField(
            model_name='plans',
            name='kind_of_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.typeofplan'),
        ),
        migrations.AddField(
            model_name='plans',
            name='number_of_weeks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.weeks'),
        ),
    ]
