# Generated by Django 3.2 on 2022-01-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220130_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name_plural': 'Plans'},
        ),
        migrations.AlterModelOptions(
            name='weeks',
            options={'verbose_name_plural': 'Weeks'},
        ),
    ]
